name: Generate RDP File

on:
  push:
    branches:
      - main

jobs:
  generate-rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate RDP File
      run: |
        $RdpFileContent = @"
        screen mode id:i:2
        desktopwidth:i:1920
        desktopheight:i:1080
        session bpp:i:32
        winposstr:s:0,3,0,0,800,600
        full address:s:127.0.0.1
        compression:i:1
        keyboardhook:i:2
        audiomode:i:0
        redirectprinters:i:1
        redirectcomports:i:0
        redirectsmartcards:i:1
        redirectclipboard:i:1
        redirectposdevices:i:0
        autoreconnection enabled:i:1
        username:s:Administrator
        domain:s:
        alternate shell:s:
        shell working directory:s:
        password 51:b:0000000000000000000000000000000000000000000000000000000000000000
        disable wallpaper:i:0
        disable full window drag:i:1
        disable menu anims:i:1
        disable themes:i:0
        bitmapcachepersistenable:i:1
        "@

        $RdpFilePath = "$env:GITHUB_WORKSPACE\remote-desktop.rdp"
        Set-Content -Path $RdpFilePath -Value $RdpFileContent
      shell: pwsh

    - name: Upload RDP File
      uses: actions/upload-artifact@v4
      with:
        name: remote-desktop
        path: ${{ github.workspace }}/remote-desktop.rdp
