name: Enable RDP on GitHub Runner

on:
  workflow_dispatch:

jobs:
  enable-rdp:
    runs-on: windows-latest

    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set RDP Password
        run: |
          net user administrator YourSecurePassword123
          net user administrator /active:yes

      - name: Download and Setup Ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath ngrok

      - name: Authenticate Ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.2sXEjjaDPFuI9xLzMmYkz18YrxS_37otnTB16e2ybqPceAreZ }}

      - name: Start RDP Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
